force-app/main/default/objects/Account/fields/Added_to_Call_List__c.field-meta.xml
<CustomField>
    <fullName>Added_to_Call_List__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Added to Call List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/getRecords.cls
public with sharing class getRecords {
    @AuraEnabled(cacheable=true)
    public static List<Object> getData(String objectType){
        try {
            // String query = objectType =='Account'?'SELECT Id, Name, Email__c, Phone FROM '+objectType+' WHERE Phone != null AND Added_to_Call_List__c = false LIMIT 10':'SELECT Id, Name, Account.Name, Email, Phone FROM '+ objectType+' WHERE Phone != null AND Added_to_Call_List__c = false LIMIT 10';
            String query = 'SELECT Id, Name, Account.Name, Email, Phone FROM '+ objectType+' WHERE Phone != null AND Added_to_Call_List__c = false LIMIT 10';
            return Database.query(query);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}